services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lingovector
    ports:
      - "5432:5432"
    volumes:
      - lingovector-postgres:/var/lib/postgresql/data

volumes:
  lingovector-postgres:
